### ISSUE TITLE
正在加载数据（下拉刷新）时，点击底部切换 fragment ，会出现重叠

### ISSUE THREAD

**Issue by Dkaishu** [lovejjfg/Readhub#1]
感觉隐藏view或者干脆取消网络请求更好一些吧

**Comment by lovejjfg** [comment]
就是那个 Loading 的小圆圈会重叠是吧？[0.0.4](https://github.com/lovejjfg/Readhub/releases/tag/0.0.4)这版本应该没有这个问题啦。请切到 gradle_2.3.3 的分支哟。
