### ISSUE TITLE
你好，请问为什么计划去掉dataBinding呢

### ISSUE THREAD

**Issue by franticn** [lovejjfg/Readhub#2]
rt

**Comment by lovejjfg** [comment]
我不是还没有去掉的嘛，主要是觉得没什么大用处，kotlin 里面也不用你去 findviewById 了。

**Comment by lovejjfg** [comment]
https://github.com/lovejjfg/Readhub/commit/fee44be34ed6ad368249936febfe67c6da38cc1e 已经正式移除 dataBinding
